### ISSUE TITLE
Complete their Profile=Open Invitation for Spam

### ISSUE THREAD

**Issue by eurobank** [MercanoG/Osclass-Enterprise#6]
https://github.com/MercanoG/Osclass-Enterprise/commit/d354cc2859df11939bb16e334a45969d2c2241db

We do not allow users that have zero ads or/and are new to do anything with their profile.

Your commit is not a good idea.

**Comment by Tangol** [comment]
@eurobank After they create an account, how do you restrict their access to the profile page?
And how is this related to spam?

I added this because users were creating shallow accounts and went directly for posting listings.
So I wanted to prompt them to complete their profile (phone number, address, description etc.) before posting.
Also, this works well with the Pay Plugin's eCommerce feature, as users need to complete their profile before placing an order.

**Comment by eurobank** [comment]
They put links etc in their profile. Or you mean something else?

I limit them using this:

`
function wm_user_edit_disable($errors, $uid) {
    $itemCount = Item::newInstance()->countByUserID($uid);
    if($itemCount < 1) { // Less than 1 items.
        $errors.= 'You need to have more ads to edit your profile.' . PHP_EOL;
    }

    $user = User::newInstance()->findByPrimaryKey($uid);
    $dateNow = new DateTime('now');
    $dateRegister = new DateTime($user['dt_reg_date']);
    $dateDifference = $dateNow->diff($dateRegister);
    if($dateDifference->days < 2) { // Less than 2 days passed since register.
        $errors.= 'Your account is very new, please try again after a few days.' . PHP_EOL;
    }

    return $errors;
}
osc_add_filter('user_edit_flash_error', 'wm_user_edit_disable');
`

**Comment by Tangol** [comment]
The 2 functions you're using aren't necessary anymore because of the following reasons:

1. **7G Firewall** that gets activated when you activate the Permalinks - blocks most bots.
2. Updated **Robots.txt** in Osclass Enterprise - stops the bots that the firewall didn't catch.
3. Integrated **Anti Spam & Protection System v2.0** - you can create rules against spam patterns.
4. I did some 'hidden' work on validating some fields to better protect against bots/fake users.

With those 2 restrictions, you're actually annoying your legit users, making them leave your platform (you're not going to see that on OLX, Gumtree etc.)
What harm can a user do by using a link in his profile description?

**Comment by eurobank** [comment]
Ok, that was only my opinion about something you added. Nothing else.

**Comment by Tangol** [comment]
@eurobank thanks for the feedback.
If you have your own specific use case, then you can revert my changes in your setup, and do your thing.
But again, it's not recommended as users need to be encouraged to complete their profiles. Some platforms even reward them for this.

Pro tip: if you want 99% legit users on your website, then use [this plugin](https://osclasspoint.com/osclass-plugins/messaging-and-communication/sms-notification-and-verification-plugin-i104) (that I've also contributed to). 😉
